### ISSUE TITLE
Dependency on HAML

### ISSUE THREAD

**Issue by fschwahn** [logankoester/errship#4]
Hi,
I really like the gem, but the dependency on haml seems like overkill for a single template. I know it's a question of taste, but pulling in a gem for rendering a single template seems a bit much. Maybe it is possible to make the dependency conditional and use haml if it is available and erb otherwise?

Anyway, thanks a lot!
Fabian

**Comment by logankoester** [comment]
This is the second time I've heard this request, so I am inclined to agree that it does bother some people. Open a pull request with the template converted to erb and I will be happy to merge it in as a 2.1 version. :-)

**Comment by logankoester** [comment]
I've merged your pull request, removed the remaining optional dependency on HAML (and its version of the template), updated the README changelog and released it as version 2.1.0. Thanks!
