### ISSUE TITLE
Extending View Template?

### ISSUE THREAD

**Issue by conradwt** [logankoester/errship#7]
Is there an easy way to add additional content to the view template?  I need to add a content_for to add content to another location with the DOM.

**Comment by lexifyi** [comment]
I don't believe there is an easy way to do this without forking it yourself, but you can override which views are rendered entirely by defining `render_404_error` and `render_error` in your controller. For example:

```
def render_404_error(exception = nil)
  if request.format.nil? or !request.format.html? # Gracefully handles poorly-written bots and mobile clients
    head 404
  else
    render 'errors/404'
  end
end
```

_EDIT: Woops, sorry guys. Hit Comment and Close instead of Comment._

**Comment by logankoester** [comment]
1 month inactive, considering this issue closed with @bfrydl's solution.
